/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.1
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WarrantyLife);
  }
}(this, function(expect, WarrantyLife) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WarrantyLife.Customer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customer', function() {
    it('should create an instance of Customer', function() {
      // uncomment below and update the code to test Customer
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be.a(WarrantyLife.Customer);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property refId (base name: "refId")', function() {
      // uncomment below and update the code to test the property refId
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property orderRefId (base name: "orderRefId")', function() {
      // uncomment below and update the code to test the property orderRefId
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property customerUrl (base name: "customerUrl")', function() {
      // uncomment below and update the code to test the property customerUrl
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property salesRepEmail (base name: "salesRepEmail")', function() {
      // uncomment below and update the code to test the property salesRepEmail
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "streetAddress")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property isWalkIn (base name: "isWalkIn")', function() {
      // uncomment below and update the code to test the property isWalkIn
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

    it('should have the property optIn (base name: "optIn")', function() {
      // uncomment below and update the code to test the property optIn
      //var instance = new WarrantyLife.Customer();
      //expect(instance).to.be();
    });

  });

}));
