/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.1
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WarrantyLife);
  }
}(this, function(expect, WarrantyLife) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WarrantyLife.Item();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Item', function() {
    it('should create an instance of Item', function() {
      // uncomment below and update the code to test Item
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be.a(WarrantyLife.Item);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property refId (base name: "refId")', function() {
      // uncomment below and update the code to test the property refId
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property orderRefId (base name: "orderRefId")', function() {
      // uncomment below and update the code to test the property orderRefId
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property dateOfPurchase (base name: "dateOfPurchase")', function() {
      // uncomment below and update the code to test the property dateOfPurchase
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property productSku (base name: "productSku")', function() {
      // uncomment below and update the code to test the property productSku
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property purchasedCondition (base name: "purchasedCondition")', function() {
      // uncomment below and update the code to test the property purchasedCondition
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property contractYears (base name: "contractYears")', function() {
      // uncomment below and update the code to test the property contractYears
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property pricePaid (base name: "pricePaid")', function() {
      // uncomment below and update the code to test the property pricePaid
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property pricePaidCurrencyCode (base name: "pricePaidCurrencyCode")', function() {
      // uncomment below and update the code to test the property pricePaidCurrencyCode
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property taxPaid (base name: "taxPaid")', function() {
      // uncomment below and update the code to test the property taxPaid
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property shippingPaid (base name: "shippingPaid")', function() {
      // uncomment below and update the code to test the property shippingPaid
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property serialNumber (base name: "serialNumber")', function() {
      // uncomment below and update the code to test the property serialNumber
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property serialNumberType (base name: "serialNumberType")', function() {
      // uncomment below and update the code to test the property serialNumberType
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property isRepaired (base name: "isRepaired")', function() {
      // uncomment below and update the code to test the property isRepaired
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property hasDamage (base name: "hasDamage")', function() {
      // uncomment below and update the code to test the property hasDamage
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

    it('should have the property categoryId (base name: "categoryId")', function() {
      // uncomment below and update the code to test the property categoryId
      //var instance = new WarrantyLife.Item();
      //expect(instance).to.be();
    });

  });

}));
