/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.2
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WarrantyLife);
  }
}(this, function(expect, WarrantyLife) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WarrantyLife.VoucherBatch();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VoucherBatch', function() {
    it('should create an instance of VoucherBatch', function() {
      // uncomment below and update the code to test VoucherBatch
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be.a(WarrantyLife.VoucherBatch);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be();
    });

    it('should have the property qty (base name: "qty")', function() {
      // uncomment below and update the code to test the property qty
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be();
    });

    it('should have the property warrantyPlanId (base name: "warrantyPlanId")', function() {
      // uncomment below and update the code to test the property warrantyPlanId
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be();
    });

    it('should have the property voucherCodes (base name: "voucherCodes")', function() {
      // uncomment below and update the code to test the property voucherCodes
      //var instance = new WarrantyLife.VoucherBatch();
      //expect(instance).to.be();
    });

  });

}));
