/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.2
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WarrantyLife) {
      root.WarrantyLife = {};
    }
    root.WarrantyLife.Body = factory(root.WarrantyLife.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Body model module.
   * @module model/Body
   * @version 1.0.2
   */

  /**
   * Constructs a new <code>Body</code>.
   * @alias module:model/Body
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body} obj Optional instance to populate.
   * @return {module:model/Body} The populated <code>Body</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderRefId')) {
        obj['orderRefId'] = ApiClient.convertToType(data['orderRefId'], 'String');
      }
      if (data.hasOwnProperty('refId')) {
        obj['refId'] = ApiClient.convertToType(data['refId'], 'String');
      }
      if (data.hasOwnProperty('dateOfPurchase')) {
        obj['dateOfPurchase'] = ApiClient.convertToType(data['dateOfPurchase'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} orderRefId
   */
  exports.prototype['orderRefId'] = undefined;
  /**
   * @member {String} refId
   */
  exports.prototype['refId'] = undefined;
  /**
   * @member {Date} dateOfPurchase
   */
  exports.prototype['dateOfPurchase'] = undefined;



  return exports;
}));


