/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.2
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WarrantyLife) {
      root.WarrantyLife = {};
    }
    root.WarrantyLife.Warranty = factory(root.WarrantyLife.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Warranty model module.
   * @module model/Warranty
   * @version 1.0.2
   */

  /**
   * Constructs a new <code>Warranty</code>.
   * @alias module:model/Warranty
   * @class
   * @param warrantyPlanId {String} 
   * @param itemId {String} 
   * @param customerId {String} 
   */
  var exports = function(warrantyPlanId, itemId, customerId) {
    var _this = this;






    _this['warrantyPlanId'] = warrantyPlanId;
    _this['itemId'] = itemId;
    _this['customerId'] = customerId;




  };

  /**
   * Constructs a <code>Warranty</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Warranty} obj Optional instance to populate.
   * @return {module:model/Warranty} The populated <code>Warranty</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('refId')) {
        obj['refId'] = ApiClient.convertToType(data['refId'], 'String');
      }
      if (data.hasOwnProperty('registrationCode')) {
        obj['registrationCode'] = ApiClient.convertToType(data['registrationCode'], 'String');
      }
      if (data.hasOwnProperty('warrantyUrl')) {
        obj['warrantyUrl'] = ApiClient.convertToType(data['warrantyUrl'], 'String');
      }
      if (data.hasOwnProperty('orderRefId')) {
        obj['orderRefId'] = ApiClient.convertToType(data['orderRefId'], 'String');
      }
      if (data.hasOwnProperty('warrantyPlanId')) {
        obj['warrantyPlanId'] = ApiClient.convertToType(data['warrantyPlanId'], 'String');
      }
      if (data.hasOwnProperty('itemId')) {
        obj['itemId'] = ApiClient.convertToType(data['itemId'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('dateOfPurchase')) {
        obj['dateOfPurchase'] = ApiClient.convertToType(data['dateOfPurchase'], 'Date');
      }
      if (data.hasOwnProperty('pricePaid')) {
        obj['pricePaid'] = ApiClient.convertToType(data['pricePaid'], 'Number');
      }
      if (data.hasOwnProperty('pricePaidCurrencyCode')) {
        obj['pricePaidCurrencyCode'] = ApiClient.convertToType(data['pricePaidCurrencyCode'], 'String');
      }
      if (data.hasOwnProperty('taxPaid')) {
        obj['taxPaid'] = ApiClient.convertToType(data['taxPaid'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} refId
   */
  exports.prototype['refId'] = undefined;
  /**
   * @member {String} registrationCode
   */
  exports.prototype['registrationCode'] = undefined;
  /**
   * @member {String} warrantyUrl
   */
  exports.prototype['warrantyUrl'] = undefined;
  /**
   * @member {String} orderRefId
   */
  exports.prototype['orderRefId'] = undefined;
  /**
   * @member {String} warrantyPlanId
   */
  exports.prototype['warrantyPlanId'] = undefined;
  /**
   * @member {String} itemId
   */
  exports.prototype['itemId'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {Date} dateOfPurchase
   */
  exports.prototype['dateOfPurchase'] = undefined;
  /**
   * @member {Number} pricePaid
   */
  exports.prototype['pricePaid'] = undefined;
  /**
   * @member {module:model/Warranty.PricePaidCurrencyCodeEnum} pricePaidCurrencyCode
   */
  exports.prototype['pricePaidCurrencyCode'] = undefined;
  /**
   * @member {Number} taxPaid
   */
  exports.prototype['taxPaid'] = undefined;


  /**
   * Allowed values for the <code>pricePaidCurrencyCode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PricePaidCurrencyCodeEnum = {
    /**
     * value: "USD"
     * @const
     */
    "USD": "USD",
    /**
     * value: "CAD"
     * @const
     */
    "CAD": "CAD"  };


  return exports;
}));


