/**
 * Warranty Life API
 * Warranty life Api
 *
 * OpenAPI spec version: 1.0.8
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WarrantyLifeApi);
  }
}(this, function(expect, WarrantyLifeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WarrantyLifeApi.CustomersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomersApi', function() {
    describe('customersCustomerIdGet', function() {
      it('should call customersCustomerIdGet successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdGet
        //instance.customersCustomerIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersGet', function() {
      it('should call customersGet successfully', function(done) {
        //uncomment below and update the code to test customersGet
        //instance.customersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersPost', function() {
      it('should call customersPost successfully', function(done) {
        //uncomment below and update the code to test customersPost
        //instance.customersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
