/**
 * Warranty Life
 * Warranty life api definition for openapi 3.0.0 from here we generate api's
 *
 * OpenAPI spec version: 1.0.1
 * Contact: jeff.durand@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WarrantyLife);
  }
}(this, function(expect, WarrantyLife) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WarrantyLife.WarrantiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WarrantiesApi', function() {
    describe('itemsItemIdWarrantiesPost', function() {
      it('should call itemsItemIdWarrantiesPost successfully', function(done) {
        //uncomment below and update the code to test itemsItemIdWarrantiesPost
        //instance.itemsItemIdWarrantiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('warrantiesGet', function() {
      it('should call warrantiesGet successfully', function(done) {
        //uncomment below and update the code to test warrantiesGet
        //instance.warrantiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('warrantiesPost', function() {
      it('should call warrantiesPost successfully', function(done) {
        //uncomment below and update the code to test warrantiesPost
        //instance.warrantiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('warrantiesWarrantyIdDelete', function() {
      it('should call warrantiesWarrantyIdDelete successfully', function(done) {
        //uncomment below and update the code to test warrantiesWarrantyIdDelete
        //instance.warrantiesWarrantyIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('warrantiesWarrantyIdGet', function() {
      it('should call warrantiesWarrantyIdGet successfully', function(done) {
        //uncomment below and update the code to test warrantiesWarrantyIdGet
        //instance.warrantiesWarrantyIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
